apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontent-deployment"
  namespace: "2048-game"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - image: 548802605325.dkr.ecr.us-east-1.amazonaws.com/my-cicd
        imagePullPolicy: Always
        name: "frondend"
        ports:
        - containerPort: 80
